# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dfl_service_pb2 as dfl__service__pb2

GRPC_GENERATED_VERSION = '1.48.0'
GRPC_VERSION = grpc.__version__

try:
    from grpc._utilities import first_version_is_lower
    if first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION):
        warnings.warn(
            f'grpcio {GRPC_VERSION} is older than the generated stubs require '
            f'(>={GRPC_GENERATED_VERSION}). Consider upgrading grpcio.',
            RuntimeWarning
        )
except ImportError:
    pass


class DFLServiceStub(object):
    """Stub for the DFLService — used by gRPC clients (gossip senders)."""

    def __init__(self, channel):
        self.GossipWeights = channel.unary_unary(
            '/dfl.DFLService/GossipWeights',
            request_serializer=dfl__service__pb2.WeightRequest.SerializeToString,
            response_deserializer=dfl__service__pb2.WeightResponse.FromString,
            _registered_method=True,
        )


class DFLServiceServicer(object):
    """Servicer base class — subclass this in node.py."""

    def GossipWeights(self, request, context):
        """A node sends its local model weights to a peer."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DFLServiceServicer_to_server(servicer, server):
    """Register the DFLServiceServicer implementation on a gRPC server."""
    rpc_method_handlers = {
        'GossipWeights': grpc.unary_unary_rpc_method_handler(
            servicer.GossipWeights,
            request_deserializer=dfl__service__pb2.WeightRequest.FromString,
            response_serializer=dfl__service__pb2.WeightResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'dfl.DFLService', rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dfl.DFLService', rpc_method_handlers)


class DFLService(object):
    """Experimental unary API helper."""

    @staticmethod
    def GossipWeights(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfl.DFLService/GossipWeights',
            dfl__service__pb2.WeightRequest.SerializeToString,
            dfl__service__pb2.WeightResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )